name: Bug report
description: Something is broken
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Tell what you saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result
    validations:
      required: true
