name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it useful?
    validations:
      required: true
