name: Docs Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    name: Lint Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md

  link-check:
    name: Check links in Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
            args: >
              args: >
                --no-progress
                --md
                --exclude-mail
                --exclude "localhost"
                --exclude "127.0.0.1"
                --exclude "example.com"
                --exclude "example.org"
                --exclude "example.net"
                --exclude "img.shields.io"
                --exclude "githubusercontent.com"
                --exclude "php.net"
                --exclude "https://*"     # ignore all external URLs
                "./**/*.md"
  
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
